# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOyou3UAMGqIPpCWqPoyf5vlXK4vwHvs
"""

import statistics

import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset
from torch.amp import autocast, GradScaler


def prepare_data() -> TensorDataset:
    X = torch.randn(10000, 128)
    y = torch.randint(0, 2, (10000,))
    return TensorDataset(X, y)


def train():
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True

    dataloader = DataLoader(
        prepare_data(),
        batch_size=256,
        shuffle=True,
        num_workers=2,
        pin_memory=True,
        persistent_workers=True,
        prefetch_factor=2,
    )

    device = torch.device("cuda")

    model = nn.Sequential(
        nn.Linear(128, 512), nn.ReLU(),
        nn.Linear(512, 128), nn.ReLU(),
        nn.Linear(128, 2)
    ).to(device).train()

    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    criterion = nn.CrossEntropyLoss()

    scaler = GradScaler('cuda')

    losses_history = []
    forward_events = []
    backward_events = []

    for batch_idx, (data, target) in enumerate(dataloader):
        data = data.to(device, non_blocking=True)
        target = target.to(device, non_blocking=True)

        noise = torch.randn_like(data)
        data = data + noise

        optimizer.zero_grad(set_to_none=True)

        fwd_start = torch.cuda.Event(enable_timing=True)
        fwd_end = torch.cuda.Event(enable_timing=True)
        bwd_start = torch.cuda.Event(enable_timing=True)
        bwd_end = torch.cuda.Event(enable_timing=True)

        fwd_start.record()

        with autocast('cuda'):
            output = model(data)
            loss = criterion(output, target)

        fwd_end.record()

        bwd_start.record()
        scaler.scale(loss).backward()
        bwd_end.record()

        scaler.step(optimizer)
        scaler.update()

        forward_events.append((fwd_start, fwd_end))
        backward_events.append((bwd_start, bwd_end))

        losses_history.append(loss.detach().item())

        if batch_idx % 20 == 0:
            print(f"Batch {batch_idx} loss: {loss.item():.4f}")

    torch.cuda.synchronize()

    forward_times = [s.elapsed_time(e) / 1000.0 for s, e in forward_events[1:]]
    backward_times = [s.elapsed_time(e) / 1000.0 for s, e in backward_events[1:]]

    print(
        f"Epoch finished, avg forward time is {statistics.mean(forward_times)}, "
        f"avg backward time is {statistics.mean(backward_times)}"
    )


if __name__ == '__main__':
    train()